Repository AY2425S1-CS2103-F13-1/tp, pull requests merged in 2024-10, with the labels that each got.

#77 Update Developer Guide with SpleetWaise NFRs
  docs/_includes/AboutUs/qianbo.md
  docs/_includes/DeveloperGuide/Requirements/03_non_functional_requirements.md
Labels: type.Chore, priority.Medium

#76 Add 8 use cases to DG
  docs/_includes/DeveloperGuide/Requirements/02_use_cases.md
Labels: type.Chore

#87 Set up `spleetwaise.transaction` package
  src/main/java/spleetwaise/address/MainApp.java
  src/main/java/spleetwaise/address/logic/LogicManager.java
  src/main/java/spleetwaise/address/logic/parser/AddressBookParser.java
  src/main/java/spleetwaise/address/model/ModelManager.java
  src/main/java/spleetwaise/transaction/logic/commands/AddCommand.java
  src/main/java/spleetwaise/transaction/logic/commands/Command.java
  src/main/java/spleetwaise/transaction/logic/parser/TransactionParser.java
  src/main/java/spleetwaise/transaction/model/Model.java
  src/main/java/spleetwaise/transaction/model/ModelManager.java
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/address/logic/parser/AddressBookParserTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/TransactionParserTest.java
  src/test/java/spleetwaise/transaction/model/ModelManagerTest.java
  src/test/java/spleetwaise/transaction/testutil/TransactionUtil.java
Labels: priority.High

#96 Add Transaction Command
  build.gradle
  src/main/java/spleetwaise/address/logic/LogicManager.java
  src/main/java/spleetwaise/transaction/logic/commands/AddCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/AddCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/CliSyntax.java
  src/main/java/spleetwaise/transaction/logic/parser/Parser.java
  src/main/java/spleetwaise/transaction/logic/parser/ParserUtil.java
  src/main/java/spleetwaise/transaction/logic/parser/TransactionParser.java
  src/main/java/spleetwaise/transaction/model/Model.java
  src/main/java/spleetwaise/transaction/model/ModelManager.java
  src/main/java/spleetwaise/transaction/model/transaction/Amount.java
  src/main/java/spleetwaise/transaction/model/transaction/Transaction.java
  src/main/java/spleetwaise/transaction/model/transaction/TransactionIdUtil.java
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/transaction/logic/parser/CommandParserTestUtil.java
  src/test/java/spleetwaise/transaction/logic/parser/ParserUtilTest.java
  src/test/java/spleetwaise/transaction/logic/parser/TransactionParserTest.java
  src/test/java/spleetwaise/transaction/model/ModelManagerTest.java
  src/test/java/spleetwaise/transaction/model/transaction/TransactionIdUtilTest.java
  src/test/java/spleetwaise/transaction/testutil/TransactionUtil.java
Labels: priority.High

#99 Fix Logic Manager Test
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
Labels: priority.High

#104 Add listTxn command
  src/main/java/spleetwaise/transaction/logic/commands/ListCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/TransactionParser.java
  src/main/java/spleetwaise/transaction/model/Model.java
  src/main/java/spleetwaise/transaction/model/ModelManager.java
  src/main/java/spleetwaise/transaction/model/TransactionBook.java
  src/main/java/spleetwaise/transaction/model/transaction/Transaction.java
  src/main/java/spleetwaise/transaction/model/transaction/TransactionIdPredicate.java
  src/test/java/spleetwaise/transaction/logic/commands/CommandTestUtil.java
  src/test/java/spleetwaise/transaction/logic/commands/ListCommandTest.java
  src/test/java/spleetwaise/transaction/testutil/TransactionBuilder.java
  src/test/java/spleetwaise/transaction/testutil/TypicalIndexes.java
Labels: priority.High

#108 feat: add clearTxn for user testing, update User Guide with clearTxn command
  docs/UserGuide.md
  src/main/java/spleetwaise/transaction/logic/parser/TransactionParser.java
  src/test/java/spleetwaise/transaction/logic/parser/TransactionParserTest.java
Labels: type.Chore, priority.Medium, severity.VeryLow

#120 Fix formatter config
  .editorconfig
  config/Eclipse.xml
  config/InteliJ.xml
  config/IntelliJ.xml
  docs/DevOps.md
Labels: type.Chore

#115 Refactor `TransactionIdUtil` into `commons.IdUtil`
  src/main/java/spleetwaise/commons/IdUtil.java
  src/main/java/spleetwaise/transaction/model/transaction/Transaction.java
  src/main/java/spleetwaise/transaction/model/transaction/TransactionIdUtil.java
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/commons/IdUtilTest.java
  src/test/java/spleetwaise/transaction/model/transaction/TransactionIdUtilTest.java
Labels: type.Chore

#125 Update gitflow docs
  README.md
  docs/SettingUp.md
  docs/index.md
Labels: type.Chore, priority.Medium

#126 Change Amount validation
  docs/UserGuide.md
  src/main/java/spleetwaise/transaction/model/transaction/Amount.java
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/transaction/model/ModelManagerTest.java
  src/test/java/spleetwaise/transaction/model/TransactionBookTest.java
  src/test/java/spleetwaise/transaction/model/transaction/AmountTest.java
  src/test/java/spleetwaise/transaction/model/transaction/TransactionTest.java
  src/test/java/spleetwaise/transaction/testutil/TransactionBuilder.java
  src/test/java/spleetwaise/transaction/testutil/TransactionUtil.java
  src/test/java/spleetwaise/transaction/testutil/TypicalTransactions.java
Labels: priority.High

#131 Add remark command and related functionality to addcommand and editcommand
  docs/UserGuide.md
  src/main/java/spleetwaise/address/logic/commands/AddCommand.java
  src/main/java/spleetwaise/address/logic/commands/EditCommand.java
  src/main/java/spleetwaise/address/logic/commands/RemarkCommand.java
  src/main/java/spleetwaise/address/logic/parser/AddCommandParser.java
  src/main/java/spleetwaise/address/logic/parser/AddressBookParser.java
  src/main/java/spleetwaise/address/logic/parser/CliSyntax.java
  src/main/java/spleetwaise/address/logic/parser/EditCommandParser.java
  src/main/java/spleetwaise/address/logic/parser/ParserUtil.java
  src/main/java/spleetwaise/address/logic/parser/RemarkCommandParser.java
  src/main/java/spleetwaise/address/model/person/Person.java
  src/main/java/spleetwaise/address/model/person/Remark.java
  src/main/java/spleetwaise/address/model/util/SampleDataUtil.java
  src/main/java/spleetwaise/address/storage/JsonAdaptedPerson.java
  src/main/java/spleetwaise/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateIdAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/address/logic/commands/CommandTestUtil.java
  src/test/java/spleetwaise/address/logic/commands/EditCommandTest.java
  src/test/java/spleetwaise/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/spleetwaise/address/logic/commands/RemarkCommandTest.java
  src/test/java/spleetwaise/address/logic/parser/AddressBookParserTest.java
  src/test/java/spleetwaise/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/spleetwaise/address/model/person/PersonTest.java
  src/test/java/spleetwaise/address/storage/JsonAdaptedPersonTest.java
  src/test/java/spleetwaise/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/spleetwaise/address/testutil/PersonBuilder.java
  src/test/java/spleetwaise/address/testutil/PersonUtil.java
  src/test/java/spleetwaise/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High, GUI, epic.AddressBook

#95 Add TransactionCard, TransactionListPanel component, and split panel layout
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/spleetwaise/address/AppParameters.java
  src/main/java/spleetwaise/address/logic/Logic.java
  src/main/java/spleetwaise/address/logic/LogicManager.java
  src/main/java/spleetwaise/address/logic/Messages.java
  src/main/java/spleetwaise/address/ui/MainWindow.java
  src/main/java/spleetwaise/transaction/ui/TransactionCard.java
  src/main/java/spleetwaise/transaction/ui/TransactionListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/MenuBarHandle.java
  src/test/java/guitests/guihandles/NodeHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/guitests/guihandles/StageHandle.java
  src/test/java/guitests/guihandles/StatusBarHandle.java
  src/test/java/guitests/guihandles/exceptions/NodeNotFoundException.java
  src/test/java/guitests/guihandles/exceptions/StageNotFoundException.java
  src/test/java/spleetwaise/address/testutil/Assert.java
  src/test/java/systemtests/AddCommandGuiTest.java
  src/test/java/systemtests/TestApp.java
  src/test/java/systemtests/TestFxAppRunner.java
  src/test/java/systemtests/TestFxAppSetup.java
Labels: priority.High, epic.Transactions

#141 Fix storage not loaded in transaction model
  src/main/java/spleetwaise/address/MainApp.java
  src/main/java/spleetwaise/address/logic/LogicManager.java
  src/main/java/spleetwaise/address/model/util/SampleDataUtil.java
Labels: priority.High, severity.High

#149 Increment shadowJar build to 1.4
  build.gradle
Labels: type.Chore

#150 Filter Command
  docs/UserGuide.md
  docs/images/filterTxnAlexYeohResult.png
  docs/images/filterTxnBerniceYuAmt55Result.png
  docs/images/filterTxnExample.png
  src/main/java/spleetwaise/transaction/logic/commands/FilterCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/FilterCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/TransactionParser.java
  src/test/java/spleetwaise/transaction/logic/commands/FilterCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/FilterCommandParserTest.java
Labels: priority.Medium

#157 Enables gradle assert in build.gradle
  build.gradle
Labels: priority.Medium

#163 Add bugfix split panel layout with min width
  src/main/java/spleetwaise/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.High

#171 Update ArchitectureDiagram.puml
  docs/diagrams/ArchitectureDiagram.puml
Labels: type.Chore, priority.High

#182 166 Update UI class diagram
  docs/_includes/DeveloperGuide/Design/ui.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Chore, priority.High, GUI

#178 167 puml storage
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Chore, priority.High, epic.Transactions

#179 164 new right pane UI
  src/main/java/spleetwaise/address/ui/MainWindow.java
  src/main/java/spleetwaise/transaction/ui/RightPanel.java
  src/main/java/spleetwaise/transaction/ui/TransactionCard.java
  src/main/java/spleetwaise/transaction/ui/TransactionListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RightPanel.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: priority.Medium, epic.Transactions, GUI

#173 172 addcommand categories tag and storage
  src/main/java/spleetwaise/address/logic/parser/CliSyntax.java
  src/main/java/spleetwaise/address/model/util/SampleDataUtil.java
  src/main/java/spleetwaise/address/storage/JsonAdaptedTag.java
  src/main/java/spleetwaise/transaction/logic/commands/AddCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/AddCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/CliSyntax.java
  src/main/java/spleetwaise/transaction/logic/parser/ParserUtil.java
  src/main/java/spleetwaise/transaction/model/transaction/Category.java
  src/main/java/spleetwaise/transaction/model/transaction/Date.java
  src/main/java/spleetwaise/transaction/model/transaction/Transaction.java
  src/main/java/spleetwaise/transaction/storage/adapters/JsonAdaptedCategory.java
  src/main/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransaction.java
  src/test/data/JsonSerializableTransactionBookTest/typicalTransactionBook.json
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/address/logic/commands/DeleteCommandTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/transaction/model/ModelManagerTest.java
  src/test/java/spleetwaise/transaction/model/TransactionBookTest.java
  src/test/java/spleetwaise/transaction/model/transaction/CategoryTest.java
  src/test/java/spleetwaise/transaction/model/transaction/DescriptionTest.java
  src/test/java/spleetwaise/transaction/model/transaction/TransactionTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedCategoryTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransactionTest.java
  src/test/java/spleetwaise/transaction/testutil/TransactionBuilder.java
Labels: priority.High

#185 Fixes codecov by updating GH Actions and build.gradle
  .github/workflows/gradle.yml
  build.gradle
Labels: priority.High

#195 fix remark add command empty input
  src/main/java/spleetwaise/address/logic/parser/AddCommandParser.java
  src/main/java/spleetwaise/address/model/person/Remark.java
  src/test/java/spleetwaise/address/logic/commands/CommandTestUtil.java
  src/test/java/spleetwaise/address/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/address/logic/parser/ParserUtilTest.java
  src/test/java/spleetwaise/address/model/person/RemarkTest.java
  src/test/java/spleetwaise/address/testutil/PersonUtil.java
  src/test/java/systemtests/AddCommandGuiTest.java
Labels: type.Enhancement, priority.High, epic.AddressBook, alpha-bug

#203 Implement predicate for filterCommand
  src/main/java/spleetwaise/transaction/logic/commands/AddCommand.java
  src/main/java/spleetwaise/transaction/logic/commands/FilterCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/FilterCommandParser.java
  src/main/java/spleetwaise/transaction/model/FilterCommandPredicate.java
  src/test/java/spleetwaise/transaction/logic/commands/FilterCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/FilterCommandParserTest.java
  src/test/java/spleetwaise/transaction/model/FilterCommandPredicateTest.java
Labels: severity.High

#197 Enhance addTxn to support using person index
  src/main/java/spleetwaise/transaction/logic/commands/AddCommand.java
  src/main/java/spleetwaise/transaction/logic/commands/ClearCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/AddCommandParser.java
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/transaction/testutil/TransactionUtil.java
Labels: type.Enhancement, priority.High, epic.Transactions, do not merge

#205 Allow Name Input with more Legal Names
  docs/UserGuide.md
  src/main/java/spleetwaise/address/logic/parser/ParserUtil.java
  src/main/java/spleetwaise/address/model/person/Name.java
  src/test/java/spleetwaise/address/logic/commands/CommandTestUtil.java
  src/test/java/spleetwaise/address/model/person/NameTest.java
Labels: type.Enhancement, severity.High, alpha-bug

#217 Fix `MESSAGE_USAGE` for editTxn
  src/main/java/spleetwaise/transaction/logic/commands/EditCommand.java
Labels: alpha-bug

#218 Update `editTxn` UG
  docs/UserGuide.md
Labels: alpha-bug
