Repository AY2425S1-CS2103-F13-1/tp, pull requests merged in 2024-09, with the labels that each got.

#47 Update AboutUs.md with personal information
  docs/AboutUs.md
  docs/_config.yml
  docs/team/seeyangzhi.md
Labels: type.Chore, priority.Medium

#56 Update AboutUs.md with personal details
  docs/AboutUs.md
Labels: type.Chore

#50 Update `README.md`
  README.md
  docs/images/Ui.png
Labels: type.Chore, severity.VeryLow
