Repository AY2425S1-CS2103-F13-1/tp, pull requests merged in 2024-11, with the labels that each got.

#225 Remove id from `Transaction.toString()`
  src/main/java/spleetwaise/transaction/model/transaction/Transaction.java
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/model/transaction/TransactionTest.java
Labels: alpha-bug

#213 36 Add mark, unmark transactions, bugfix
  docs/UserGuide.md
  src/main/java/spleetwaise/address/logic/commands/EditCommand.java
  src/main/java/spleetwaise/commons/model/CommonModel.java
  src/main/java/spleetwaise/transaction/logic/commands/EditCommand.java
  src/main/java/spleetwaise/transaction/logic/commands/MarkCommand.java
  src/main/java/spleetwaise/transaction/logic/commands/UnmarkCommand.java
  src/main/java/spleetwaise/transaction/logic/commands/UpdateStatusCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/MarkCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/TransactionParser.java
  src/main/java/spleetwaise/transaction/logic/parser/UnmarkCommandParser.java
  src/main/java/spleetwaise/transaction/model/TransactionBookModel.java
  src/main/java/spleetwaise/transaction/model/TransactionBookModelManager.java
  src/main/java/spleetwaise/transaction/model/transaction/Status.java
  src/main/java/spleetwaise/transaction/model/transaction/Transaction.java
  src/main/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransaction.java
  src/main/java/spleetwaise/transaction/ui/TransactionCard.java
  src/main/resources/images/done_icon.png
  src/main/resources/view/TransactionListCard.fxml
  src/test/data/JsonSerializableTransactionBookTest/duplicateEntryTransactionBook.json
  src/test/data/JsonSerializableTransactionBookTest/duplicateIdTransactionBook.json
  src/test/data/JsonSerializableTransactionBookTest/invalidEntryTransactionBook.json
  src/test/data/JsonSerializableTransactionBookTest/typicalTransactionBook.json
  src/test/java/spleetwaise/address/logic/LogicManagerTest.java
  src/test/java/spleetwaise/address/logic/commands/EditCommandTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/commands/CommandTestUtil.java
  src/test/java/spleetwaise/transaction/logic/commands/EditCommandTest.java
  src/test/java/spleetwaise/transaction/logic/commands/EditTransactionDescriptorTest.java
  src/test/java/spleetwaise/transaction/logic/commands/MarkCommandTest.java
  src/test/java/spleetwaise/transaction/logic/commands/UnmarkCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/MarkCommandParserTest.java
  src/test/java/spleetwaise/transaction/logic/parser/UnmarkCommandParserTest.java
  src/test/java/spleetwaise/transaction/model/transaction/TransactionTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransactionTest.java
  src/test/java/spleetwaise/transaction/testutil/TypicalTransactions.java
Labels: priority.High, epic.Transactions, GUI, alpha-bug

#230 Update Glossary and manual testing guide
  docs/DeveloperGuide.md
  docs/_includes/DeveloperGuide/Requirements/04_glossary.md
  docs/_includes/DeveloperGuide/Requirements/index.md
Labels: priority.High, epic.Transactions, type.documentation, discussion

#224 Save address book and transaction book on quit
  src/main/java/spleetwaise/address/MainApp.java
Labels: alpha-bug

#221 Add ParserUtils.getPersonFromIndex
  src/main/java/spleetwaise/address/model/AddressBook.java
  src/main/java/spleetwaise/address/model/AddressBookModel.java
  src/main/java/spleetwaise/address/model/AddressBookModelManager.java
  src/main/java/spleetwaise/commons/model/CommonModel.java
  src/main/java/spleetwaise/transaction/logic/commands/AddCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/AddCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/ParserUtil.java
  src/test/java/spleetwaise/address/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/transaction/logic/parser/ParserUtilTest.java
Labels: type.Enhancement, priority.High

#233 Add shutDownHook to execute stop()
  src/main/java/spleetwaise/address/MainApp.java
Labels: priority.High, alpha-bug

#237 Rename UG AB3 References
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/spleetwaise/address/MainApp.java
Labels: priority.High, alpha-bug

#244 Update Date Validation
  src/main/java/spleetwaise/transaction/model/transaction/Date.java
  src/test/java/spleetwaise/transaction/model/transaction/DateTest.java
Labels: priority.High, alpha-bug

#242 Abstract ive and data loading exception
  src/main/java/spleetwaise/address/MainApp.java
  src/main/java/spleetwaise/address/commons/util/ConfigUtil.java
  src/main/java/spleetwaise/address/commons/util/JsonUtil.java
  src/main/java/spleetwaise/address/logic/parser/RemarkCommandParser.java
  src/main/java/spleetwaise/address/storage/AddressBookStorage.java
  src/main/java/spleetwaise/address/storage/JsonAdaptedPerson.java
  src/main/java/spleetwaise/address/storage/JsonAdaptedTag.java
  src/main/java/spleetwaise/address/storage/JsonAddressBookStorage.java
  src/main/java/spleetwaise/address/storage/JsonSerializableAddressBook.java
  src/main/java/spleetwaise/address/storage/JsonUserPrefsStorage.java
  src/main/java/spleetwaise/address/storage/Storage.java
  src/main/java/spleetwaise/address/storage/StorageManager.java
  src/main/java/spleetwaise/address/storage/UserPrefsStorage.java
  src/main/java/spleetwaise/commons/exceptions/DataLoadingException.java
  src/main/java/spleetwaise/commons/exceptions/IllegalValueException.java
  src/main/java/spleetwaise/commons/logic/parser/exceptions/ParseException.java
  src/main/java/spleetwaise/transaction/storage/JsonSerializableTransactionBook.java
  src/main/java/spleetwaise/transaction/storage/JsonTransactionBookStorage.java
  src/main/java/spleetwaise/transaction/storage/TransactionBookStorage.java
  src/main/java/spleetwaise/transaction/storage/adapters/JsonAdaptedAmount.java
  src/main/java/spleetwaise/transaction/storage/adapters/JsonAdaptedCategory.java
  src/main/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransaction.java
  src/test/java/spleetwaise/address/commons/util/ConfigUtilTest.java
  src/test/java/spleetwaise/address/storage/JsonAdaptedPersonTest.java
  src/test/java/spleetwaise/address/storage/JsonAddressBookStorageTest.java
  src/test/java/spleetwaise/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/spleetwaise/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/spleetwaise/transaction/storage/JsonTransactionBookStorageTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedAmountTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedCategoryTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransactionTest.java
  src/test/java/systemtests/TestApp.java
Labels: type.Chore

#245 Change FilterCommandParser to accept index instead of phone number
  docs/UserGuide.md
  src/main/java/spleetwaise/address/model/AddressBook.java
  src/main/java/spleetwaise/address/model/AddressBookModelManager.java
  src/main/java/spleetwaise/transaction/logic/parser/FilterCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/ParserUtil.java
  src/test/java/spleetwaise/transaction/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/transaction/logic/parser/FilterCommandParserTest.java
Labels: priority.High

#251 Add deleteTxn UG
  docs/UserGuide.md
Labels: alpha-bug, type.documentation

#255 Update addTxn UG description
  docs/UserGuide.md
Labels: alpha-bug, type.documentation

#261 Move Main, MainApp and UI to commons
  build.gradle
  docs/DeveloperGuide.md
  docs/SettingUp.md
  src/main/java/spleetwaise/commons/Main.java
  src/main/java/spleetwaise/commons/MainApp.java
  src/main/java/spleetwaise/commons/ui/CommandBox.java
  src/main/java/spleetwaise/commons/ui/HelpWindow.java
  src/main/java/spleetwaise/commons/ui/MainWindow.java
  src/main/java/spleetwaise/commons/ui/PersonCard.java
  src/main/java/spleetwaise/commons/ui/PersonListPanel.java
  src/main/java/spleetwaise/commons/ui/ResultDisplay.java
  src/main/java/spleetwaise/commons/ui/StatusBarFooter.java
  src/main/java/spleetwaise/commons/ui/Ui.java
  src/main/java/spleetwaise/commons/ui/UiManager.java
  src/main/java/spleetwaise/commons/ui/UiPart.java
  src/main/java/spleetwaise/commons/util/AppUtil.java
  src/main/java/spleetwaise/transaction/ui/RightPanel.java
  src/main/java/spleetwaise/transaction/ui/TransactionCard.java
  src/main/java/spleetwaise/transaction/ui/TransactionListPanel.java
  src/test/java/spleetwaise/commons/ui/TestFxmlObject.java
  src/test/java/spleetwaise/commons/ui/UiPartTest.java
  src/test/java/systemtests/TestApp.java
  src/test/java/systemtests/TestFxAppRunner.java
  src/test/resources/view/UiPartTest/validFile.fxml
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: type.Chore, priority.High, severity.High

#249 Update remark related validation
  src/main/java/spleetwaise/address/logic/parser/ParserUtil.java
  src/main/java/spleetwaise/address/model/person/Person.java
  src/main/java/spleetwaise/address/model/person/Remark.java
  src/main/java/spleetwaise/address/storage/JsonAdaptedPerson.java
  src/test/java/spleetwaise/address/logic/parser/ParserUtilTest.java
  src/test/java/spleetwaise/address/model/person/RemarkTest.java
  src/test/java/spleetwaise/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High, epic.AddressBook, alpha-bug

#257 Update DG for addTxn
  docs/DeveloperGuide.md
Labels: alpha-bug, type.documentation

#269 Rename app title
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#236 181 custom filter UI and interactions
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/spleetwaise/commons/model/CommonModel.java
  src/main/java/spleetwaise/commons/ui/CommandBox.java
  src/main/java/spleetwaise/commons/ui/MainWindow.java
  src/main/java/spleetwaise/transaction/model/TransactionBookModel.java
  src/main/java/spleetwaise/transaction/model/TransactionBookModelManager.java
  src/main/java/spleetwaise/transaction/ui/RightPanel.java
  src/main/java/spleetwaise/transaction/ui/TransactionListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RightPanel.fxml
  src/test/java/systemtests/RightPanelTest.java
Labels: priority.High, epic.Transactions, GUI, alpha-bug

#279 Add isStopped condition to prevent double invocation
  src/main/java/spleetwaise/commons/MainApp.java
Labels: alpha-bug

#265 250 add missing cat in txnpane
  src/main/java/spleetwaise/commons/ui/UiManager.java
  src/main/java/spleetwaise/transaction/ui/TransactionCard.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RightPanel.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: priority.High, epic.Transactions, GUI, alpha-bug

#276 Restructure Filter Command predicates
  src/main/java/spleetwaise/transaction/logic/commands/FilterCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/FilterCommandParser.java
  src/main/java/spleetwaise/transaction/model/FilterCommandPredicate.java
  src/main/java/spleetwaise/transaction/model/filterpredicate/AmountFilterPredicate.java
  src/main/java/spleetwaise/transaction/model/filterpredicate/DateFilterPredicate.java
  src/main/java/spleetwaise/transaction/model/filterpredicate/DescriptionFilterPredicate.java
  src/main/java/spleetwaise/transaction/model/filterpredicate/PersonFilterPredicate.java
  src/main/java/spleetwaise/transaction/model/filterpredicate/StatusFilterPredicate.java
  src/test/java/spleetwaise/transaction/logic/commands/FilterCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/FilterCommandParserTest.java
  src/test/java/spleetwaise/transaction/model/FilterCommandPredicateTest.java
  src/test/java/spleetwaise/transaction/model/filterpredicate/AmountFilterPredicateTest.java
  src/test/java/spleetwaise/transaction/model/filterpredicate/DateFilterPredicateTest.java
  src/test/java/spleetwaise/transaction/model/filterpredicate/DescriptionFilterPredicateTest.java
  src/test/java/spleetwaise/transaction/model/filterpredicate/PersonFilterPredicateTest.java
  src/test/java/spleetwaise/transaction/model/filterpredicate/StatusFilterPredicateTest.java
Labels: priority.High

#281 Changes to `editTxn` UG
  docs/UserGuide.md
Labels: alpha-bug, type.documentation

#283 Implement amount sign filter in filterTxn
  docs/UserGuide.md
  src/main/java/spleetwaise/transaction/logic/commands/FilterCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/CliSyntax.java
  src/main/java/spleetwaise/transaction/logic/parser/FilterCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/ParserUtil.java
  src/main/java/spleetwaise/transaction/model/filterpredicate/AmountSignFilterPredicate.java
  src/test/java/spleetwaise/transaction/logic/parser/FilterCommandParserTest.java
  src/test/java/spleetwaise/transaction/logic/parser/ParserUtilTest.java
  src/test/java/spleetwaise/transaction/model/filterpredicate/AmountSignFilterPredicateTest.java
  src/test/java/spleetwaise/transaction/model/transaction/StatusTest.java
Labels: priority.High, epic.Transactions

#285 Trim input before valid description testing
  src/main/java/spleetwaise/transaction/logic/parser/ParserUtil.java
  src/main/java/spleetwaise/transaction/model/transaction/Description.java
  src/test/java/spleetwaise/transaction/model/transaction/DescriptionTest.java
Labels: priority.High

#287 Update FilterCommandPredicate equal logic
  src/main/java/spleetwaise/transaction/model/FilterCommandPredicate.java
  src/test/java/spleetwaise/transaction/model/FilterCommandPredicateTest.java
Labels: priority.High

#288 Update model DG design documentation
  docs/_includes/DeveloperGuide/Design/model.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/TransactionModelClassDiagram.png
Labels: type.documentation

#293 Update TxnModel CD to contain Status and Category
  docs/diagrams/TransactionModelClassDiagram.puml
  docs/images/TransactionModelClassDiagram.png
Labels: priority.High

#290 229 add txn with status
  docs/UserGuide.md
  src/main/java/spleetwaise/address/logic/commands/EditCommand.java
  src/main/java/spleetwaise/address/model/util/SampleDataUtil.java
  src/main/java/spleetwaise/transaction/logic/commands/AddCommand.java
  src/main/java/spleetwaise/transaction/logic/commands/EditCommand.java
  src/main/java/spleetwaise/transaction/logic/parser/AddCommandParser.java
  src/main/java/spleetwaise/transaction/model/transaction/Transaction.java
  src/main/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransaction.java
  src/test/java/spleetwaise/address/logic/commands/DeleteCommandTest.java
  src/test/java/spleetwaise/transaction/logic/commands/AddCommandTest.java
  src/test/java/spleetwaise/transaction/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/transaction/model/ModelManagerTest.java
  src/test/java/spleetwaise/transaction/model/TransactionBookTest.java
  src/test/java/spleetwaise/transaction/model/transaction/TransactionTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransactionTest.java
  src/test/java/spleetwaise/transaction/testutil/TransactionBuilder.java
Labels: priority.Medium, epic.Transactions, alpha-bug

#299 Update UG to reflect changes of removing escape sequence
  docs/UserGuide.md
Labels: alpha-bug, type.documentation

#301 Fix minor bug in User Guide
  docs/SettingUp.md
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#302 Move common package disclaimer
  docs/DeveloperGuide.md
  docs/_includes/DeveloperGuide/Design/architecture.md
Labels: priority.High

#304 Update UG
  docs/UserGuide.md
Labels: alpha-bug, type.documentation

#308 Add bug fix during edit person name
  src/main/java/spleetwaise/address/logic/commands/EditCommand.java
Labels: severity.High, epic.Transactions, GUI, alpha-bug

#307 Fix data file edit behaviour
  src/main/java/spleetwaise/address/model/person/Address.java
  src/main/java/spleetwaise/address/model/person/Name.java
  src/main/java/spleetwaise/address/model/person/Remark.java
  src/main/java/spleetwaise/address/model/tag/Tag.java
  src/main/java/spleetwaise/address/storage/JsonAdaptedPerson.java
  src/main/java/spleetwaise/transaction/model/transaction/Amount.java
  src/main/java/spleetwaise/transaction/model/transaction/Category.java
  src/main/java/spleetwaise/transaction/model/transaction/Date.java
  src/test/java/spleetwaise/address/model/person/PersonTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedCategoryTest.java
Labels: alpha-bug

#306 291 refactor right panel filter
  src/main/java/spleetwaise/transaction/ui/RightPanel.java
  src/test/java/systemtests/RightPanelTest.java
Labels: priority.High, epic.Transactions, GUI, alpha-bug

#309 Update Class diagram of Parser Classes
  docs/UserGuide.md
  docs/_includes/DeveloperGuide/Design/architecture.md
  docs/_includes/DeveloperGuide/Design/logic.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TransactionModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/TransactionModelClassDiagram.png
Labels: priority.High

#310 Fix id errors when editing from json
  docs/UserGuide.md
  src/main/java/spleetwaise/address/storage/JsonAdaptedPerson.java
  src/main/java/spleetwaise/address/storage/JsonSerializableAddressBook.java
  src/main/java/spleetwaise/commons/util/IdUtil.java
  src/main/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransaction.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableTransactionBookTest/duplicateEntryTransactionBook.json
  src/test/data/JsonSerializableTransactionBookTest/duplicateIdTransactionBook.json
  src/test/data/JsonSerializableTransactionBookTest/invalidEntryTransactionBook.json
  src/test/data/JsonSerializableTransactionBookTest/typicalTransactionBook.json
  src/test/java/spleetwaise/address/storage/JsonAdaptedPersonTest.java
  src/test/java/spleetwaise/address/storage/JsonAddressBookStorageTest.java
  src/test/java/spleetwaise/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/spleetwaise/address/testutil/TypicalPersons.java
  src/test/java/spleetwaise/commons/util/IdUtilTest.java
  src/test/java/spleetwaise/transaction/storage/adapters/JsonAdaptedTransactionTest.java
Labels: type.Enhancement, priority.High, severity.High, epic.Transactions, epic.AddressBook, alpha-bug

#311 Bugfix label in txnpane too long
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: priority.Medium, GUI, alpha-bug

#313 312 add year on UI
  src/main/java/spleetwaise/transaction/ui/TransactionCard.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/TransactionListCard.fxml
Labels: priority.High, epic.Transactions, GUI

#317 Track balance based on txn list dynamically
  src/main/java/spleetwaise/commons/logic/Logic.java
  src/main/java/spleetwaise/commons/logic/LogicManager.java
  src/main/java/spleetwaise/commons/ui/MainWindow.java
  src/main/java/spleetwaise/transaction/ui/RightPanel.java
  src/main/resources/view/RightPanel.fxml
Labels: epic.Transactions, GUI, alpha-bug

#315 Remove not implemented use case scenarios in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_includes/DeveloperGuide/Requirements/02_use_cases.md
Labels: priority.High

#323 Change filter menu to initialize once and hide/show
  src/main/java/spleetwaise/transaction/ui/RightPanel.java
Labels: priority.High, GUI, alpha-bug

#324 Testing UI test
  build.gradle
  src/main/java/spleetwaise/commons/ui/UiManager.java
  src/test/java/spleetwaise/commons/ui/UiManagerTest.java
Labels: type.Enhancement

#325 Remove CommonModel reference
  docs/_includes/DeveloperGuide/Design/architecture.md
  docs/images/LogicClassDiagram.png
Labels: priority.High

#328 Add acknowledgements
  README.md
  docs/DeveloperGuide.md
  docs/index.md
Labels: alpha-bug, type.documentation

#333 Add additional lines related to categories in addTxn
  docs/UserGuide.md
Labels: alpha-bug, type.documentation

#337 Extract methods in FilterCommandParser
  src/main/java/spleetwaise/transaction/logic/parser/FilterCommandParser.java
Labels: priority.High

#339 Add option to track undone balance
  src/main/java/spleetwaise/transaction/ui/RightPanel.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/RightPanel.fxml
Labels: priority.Medium, epic.Transactions, GUI

#335 334 duplicated txn ug&dg documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: alpha-bug, type.documentation

#340 320 reset filter to reset toggle info
  src/main/java/spleetwaise/transaction/ui/RightPanel.java
  src/test/java/guitests/GuiRobot.java
  src/test/java/systemtests/RightPanelTest.java
Labels: priority.Medium, epic.Transactions, GUI

#344 327 update UI images
  docs/DeveloperGuide.md
  docs/images/Ui.png
  docs/images/filterTxnAlexYeohResult.png
  docs/images/filterTxnBerniceYuAmt55Result.png
  docs/images/filterTxnExample.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: priority.High, type.documentation

#342 Abstract prefixesPresent methods and Refactoring DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/spleetwaise/address/logic/parser/AddCommandParser.java
  src/main/java/spleetwaise/commons/logic/parser/BaseParserUtil.java
  src/main/java/spleetwaise/transaction/logic/parser/AddCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/EditCommandParser.java
  src/main/java/spleetwaise/transaction/logic/parser/FilterCommandParser.java
Labels: type.Enhancement, epic.Transactions, epic.AddressBook, type.documentation

#349 Add comma support for name
  src/main/java/spleetwaise/address/model/person/Name.java
  src/test/java/spleetwaise/address/model/person/NameTest.java
Labels: type.Enhancement

#347 Add wrap text to amount field
  src/main/resources/view/RightPanel.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: GUI, alpha-bug

#353 Add `clear` command should empty transaction book
  docs/UserGuide.md
  src/main/java/spleetwaise/address/logic/commands/ClearCommand.java
  src/test/java/spleetwaise/address/logic/commands/ClearCommandTest.java
Labels: priority.Medium, discussion

#356 Increment version to V1.5
  build.gradle
  src/main/java/spleetwaise/commons/MainApp.java
Labels: priority.High

#359 Remove status and category for equality check
  docs/UserGuide.md
  src/main/java/spleetwaise/transaction/model/transaction/Transaction.java
  src/test/java/spleetwaise/transaction/model/transaction/TransactionTest.java
Labels: priority.High, alpha-bug

#360 Increment ver to 1.5.1
  .codecov.yml
  build.gradle
  docs/UserGuide.md
  src/main/java/spleetwaise/commons/MainApp.java
Labels: priority.High

#361 Update name of app in log
  src/main/java/spleetwaise/commons/MainApp.java
Labels: priority.High, alpha-bug

#466 Update Partial Logic Sequence Diagram
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/LogicSequenceDiagram.png
Labels: type.documentation

#468 Update UG deleteTxn examples
  docs/UserGuide.md
Labels: type.documentation

#472 Update invalid index error message for clarity
  src/main/java/spleetwaise/address/logic/Messages.java
  src/main/java/spleetwaise/commons/logic/commands/CommandUtil.java
  src/main/java/spleetwaise/transaction/logic/parser/ParserUtil.java
  src/test/java/spleetwaise/address/logic/commands/DeleteCommandTest.java
  src/test/java/spleetwaise/address/logic/commands/EditCommandTest.java
  src/test/java/spleetwaise/commons/logic/LogicManagerTest.java
  src/test/java/spleetwaise/commons/logic/commands/CommandUtilTest.java
  src/test/java/spleetwaise/transaction/logic/parser/AddCommandParserTest.java
  src/test/java/spleetwaise/transaction/logic/parser/FilterCommandParserTest.java
Labels: type.Bug

#470 Update UG
  docs/UserGuide.md
Labels: type.documentation

#471 Update DG to remove implementation, clarify user profile and value proposition
  docs/DeveloperGuide.md
  docs/_includes/DeveloperGuide/Requirements/00_product_scope.md
  docs/_includes/DeveloperGuide/Requirements/04_glossary.md
Labels: type.documentation

#475 Fix common model interface inheritance in class diagram
  docs/diagrams/CommonModelClassDiagram.puml
  docs/images/CommonModelClassDiagram.png
Labels: type.documentation

#478 Update UG
  docs/UserGuide.md
  src/main/java/spleetwaise/address/model/person/Name.java
  src/main/java/spleetwaise/address/model/person/Person.java
Labels: type.documentation

#479 341 fix tags cat UI
  src/main/java/spleetwaise/address/ui/PersonCard.java
  src/main/java/spleetwaise/transaction/ui/TransactionCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: GUI, alpha-bug

#474 Fix bug related to wrong usage message for addTxn
  src/main/java/spleetwaise/transaction/logic/commands/AddCommand.java
Labels: type.Bug

#480 Documentation for duplicate person in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation

#482 UG clarify duplicate criteria
  docs/UserGuide.md
Labels: type.documentation

#483 id clarification for editing data files
  docs/UserGuide.md
Labels: type.documentation

#488 Standardize "undone" as "Not Done"
  docs/DeveloperGuide.md
  docs/_includes/DeveloperGuide/Requirements/02_use_cases.md
  docs/_includes/DeveloperGuide/Requirements/04_glossary.md
Labels: priority.Low, type.documentation

#489 Update UG with more detailed Amount param specification
  docs/UserGuide.md
Labels: type.documentation

#490 Update undone to done in UG
  docs/UserGuide.md
Labels: priority.Low, type.documentation

#362 Add appendices for effort and planned enhancements
  docs/DeveloperGuide.md
  docs/_includes/DeveloperGuide/Appendices/effort.md
  docs/_includes/DeveloperGuide/Appendices/planned_enhancements.md
  docs/_sass/minima/_layout.scss
Labels: do not merge

#476 Update Use Cases
  docs/_includes/DeveloperGuide/Requirements/02_use_cases.md
Labels: do not merge, type.documentation

#487 Retain the filtered state for `add` and `edit` commands
  docs/UserGuide.md
Labels: type.Bug, priority.High, epic.AddressBook

#498 Add code reuse declaration for AB4
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/MenuBarHandle.java
  src/test/java/guitests/guihandles/NodeHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/guitests/guihandles/StageHandle.java
  src/test/java/guitests/guihandles/StatusBarHandle.java
  src/test/java/guitests/guihandles/exceptions/NodeNotFoundException.java
  src/test/java/guitests/guihandles/exceptions/StageNotFoundException.java
  src/test/java/systemtests/AddCommandGuiTest.java
  src/test/java/systemtests/TestApp.java
  src/test/java/systemtests/TestFxAppRunner.java
Labels: priority.High

#499 Increment version to 1.6.0
  build.gradle
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/_includes/DeveloperGuide/Design/storage.md
  src/main/java/spleetwaise/commons/MainApp.java
Labels: priority.High
